Upgraded to new ember-cli/dependencies.
Exception: QUnit was DOWNGRADED from 1.15 to 1.14 due to bug https://github.com/stefanpenner/ember-cli/issues/1970. Keep an eye on this.